apiVersion: 1

datasources:
  - name: PostgresWeather
    type: postgres
    access: proxy
    url: postgres:5432
    user: airflow
    secureJsonData:
      password: airflow
    jsonData:
      database: weather
      sslmode: disable
      postgresVersion: 1600
      timescaledb: false
    isDefault: true
